export default {
    'bm-map': [
        'click',
        'dblclick',
        'rightclick',
        'maptypechange',
        'mousedown',
        'mousemove',
        'mouseup',
        'mouseover',
        'mouseout',
        'movestart',
        'moving',
        'moveend',
        'zoomstart',
        'zoomend',
        'addoverlay',
        'addcontrol',
        'removecontrol',
        'removeoverlay',
        'clearoverlays',
        'dragstart',
        'dragging',
        'dragend',
        'addtilelayer',
        'removetilelayer',
        'load',
        'resize'
    ],
    'bm-marker': [
        'click',
        'dblclick',
        'mousedown',
        'mouseup',
        'mouseout',
        'mouseover',
        'remove',
        'infowindowclose',
        'infowindowopen',
        'dragstart',
        'dragging',
        'dragend',
        'rightclick'
    ],
    'bm-polyline': ['click', 'dblclick', 'mousedown', 'mouseup', 'mouseout', 'mouseover', 'remove', 'lineupdate'],
    'bm-polygon': ['click', 'dblclick', 'mousedown', 'mouseup', 'mouseout', 'mouseover', 'remove', 'lineupdate'],
    'bm-circle': ['click', 'dblclick', 'mousedown', 'mouseup', 'mouseout', 'mouseover', 'remove', 'lineupdate'],
    'bm-label': ['click', 'dblclick', 'mousedown', 'mouseup', 'mouseout', 'mouseover', 'remove', 'rightclick'],
    'bm-auto-complete': ['onconfirm', 'onhighlight'],
    'bm-point-collection': ['click', 'mouseover', 'mouseout'],
    'bm-geolocation': ['locationSuccess', 'locationError'],
    'bm-overview-map': ['viewchanged', 'viewchanging'],
    'bm-context-menu': ['open', 'close']
};
